/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nucchallenge_utils_BloodPressureCuff */

#ifndef _Included_nucchallenge_utils_BloodPressureCuff
#define _Included_nucchallenge_utils_BloodPressureCuff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nucchallenge_utils_BloodPressureCuff
 * Method:    getValues
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_nucchallenge_utils_BloodPressureCuff_getValues
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
